# Stage 1: Build the application
FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /app
COPY pom.xml /app/
RUN mvn validate
COPY . /app
RUN mvn package
RUN mv ./target/demo-0.0.1-SNAPSHOT.jar ./demo-0.0.1-SNAPSHOT.jar

# Stage 2: Create the final image
FROM openjdk:17.0.1-jdk-slim-buster
COPY --from=build /app/demo-0.0.1-SNAPSHOT.jar /demo-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar","./demo-0.0.1-SNAPSHOT.jar"]
