version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.single-stage
    image: my-web-app
    container_name: maven-workshop-app
    environment: # Define environment variables for the app service
      - app.init-db=true # Set the value to true
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: maven-workshop-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: healthcheck_db
    ports:
      - "3306:3306"
